var hierarchy =
[
    [ "HirEV_SmartFitSystemsApp.Utilities.AntColonyOptimization", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ant_colony_optimization.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.AntColonyOptimization.AntPath", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ant_colony_optimization_1_1_ant_path.html", null ],
    [ "Application", null, [
      [ "HirEV_SmartFitSystemsApp.App", "d2/d00/class_hir_e_v___smart_fit_systems_app_1_1_app.html", null ]
    ] ],
    [ "global.SystemConfiguration.ApplicationSettingsBase", null, [
      [ "HirEV_SmartFitSystemsApp.Properties.Settings", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_properties_1_1_settings.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.ApproachMeasurementPair", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_approach_measurement_pair.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.ApproachPointGenerator", "d7/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_approach_point_generator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.HoleDetector.AxialRange", "dd/d03/struct_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_hole_detector_1_1_axial_range.html", null ],
    [ "BaseViewModel", null, [
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.PathItemViewModel", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_path_item_view_model.html", null ],
      [ "HirEV_SmartFitSystemsApp.ViewModel.MainViewModel", "d6/d03/class_hir_e_v___smart_fit_systems_app_1_1_view_model_1_1_main_view_model.html", null ]
    ] ],
    [ "BlockReference", null, [
      [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.SimulationBlockReference", "da/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_simulation_block_reference.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.BridgePath", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.BridgePathConsumer", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path_consumer.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.BridgePointMetadata", "d3/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_bridge_point_metadata.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.BridgeRunSnapshot", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_bridge_run_snapshot.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotTreeViewHelper.CachedColorHierarchy", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_tree_view_helper_1_1_cached_color_hierarchy.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ToolModelLoader.CachedModelData", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_tool_model_loader_1_1_cached_model_data.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotTreeViewHelper.CachedTreeViewNode", "d8/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_tree_view_helper_1_1_cached_tree_view_node.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.CADFace", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_c_a_d_face.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.CADHole", "d3/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_c_a_d_hole.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.CADHoleExportDTO", "db/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_c_a_d_hole_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointBatchCommand.ChangeInfo", "da/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command_1_1_change_info.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.CollisionAvoidanceAlgorithm", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_collision_avoidance_algorithm.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.CollisionHeuristics.CollisionCheckResult", "df/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_collision_heuristics_1_1_collision_check_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.CollisionHeuristics", "d1/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_collision_heuristics.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.CollisionAvoidanceAlgorithm.CollisionResult", "dc/d02/struct_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_collision_avoidance_algorithm_1_1_collision_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Diagnostics.PathPlanningDiagnostics.CollisionTestResult", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics_1_1_path_planning_diagnostics_1_1_collision_test_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ColorGroup", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ColorGroupedControlPointsDTO", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_color_grouped_control_points_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ColorGroupedExportDTO", "d9/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_color_grouped_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ColorGroupedMeasurementPointsDTO", "db/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_color_grouped_measurement_points_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ColorNamer", "d3/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_namer.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ColorPath", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_path.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ColorPathExportDTO", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_color_path_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ColorToolMappingUtils", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_tool_mapping_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ControlPointFilterConfig", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_control_point_filter_config.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ControlPointWithFaceIndex", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_control_point_with_face_index.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.HoleDetector.CylinderFitInfo", "db/d03/struct_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_hole_detector_1_1_cylinder_fit_info.html", null ],
    [ "Design", null, [
      [ "HirEV_SmartFitSystemsApp.Utilities.HirEVDesign", "dd/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_hir_e_v_design.html", null ],
      [ "HirEV_SmartFitSystemsApp.Windows.SectionViewDesign", "d4/d02/class_hir_e_v___smart_fit_systems_app_1_1_windows_1_1_section_view_design.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Modules.DetectedHole", "dd/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_detected_hole.html", null ],
    [ "HirEV_SmartFitSystemsApp.Windows.DimensionAnchor", "d2/d02/class_hir_e_v___smart_fit_systems_app_1_1_windows_1_1_dimension_anchor.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DiscretePath", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_discrete_path.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.DynamicToolScanner", "d9/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_dynamic_tool_scanner.html", null ],
    [ "EventArgs", null, [
      [ "HirEV_SmartFitSystemsApp.Modules.ScanPathProgressEventArgs", "d6/d03/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path_progress_event_args.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.ColorGroupEventArgs", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group_event_args.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.PathGenerationProgressEventArgs", "d9/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_generation_progress_event_args.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.SimulationEventArgs", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_simulation_event_args.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.UndoRedoEventArgs", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_redo_event_args.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotCameraUtils", "d0/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_camera_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotGeometryUtils", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_geometry_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotSelectionUtils", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_selection_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotTreeViewHelper", "d8/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_tree_view_helper.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.EyeshotVisualsManager", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_visuals_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Diagnostics.PathPlanningDiagnostics.FaceAdjacencyTestResult", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics_1_1_path_planning_diagnostic95269d81aeb6f242150fdfb71b32019e.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.FaceExtractor", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_face_extractor.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FacePoint", "df/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_face_point.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FeatureRow_DiameterBody", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_feature_row___diameter_body.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FeatureRow_DiameterHeadClearance", "d4/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_feature_row___diameter_head_clearance.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FeatureRow_MBody", "de/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_feature_row___m_body.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FeatureRow_MHeadBody", "d2/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_feature_row___m_head_body.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.FeatureRow_MPreDrill", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_feature_row___m_pre_drill.html", null ],
    [ "HirEV_SmartFitSystemsApp.FocusBehavior", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_focus_behavior.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPathManager.FrustumBounds", "d9/d00/struct_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path_manager_1_1_frustum_bounds.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.GpuDepthSnapshot", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_gpu_depth_snapshot.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.VisibilityGraphPathfinder.GraphEdge", "df/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder_1_1_graph_edge.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.VisibilityGraphPathfinder.GraphNode", "d7/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder_1_1_graph_node.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.GridPointGenerator.GridConfig", "d2/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_grid_point_generator_1_1_grid_config.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.GridPointGenerator", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_grid_point_generator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.HighZTransition", "df/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_high_z_transition.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.HoleAxisExtractor", "db/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_hole_axis_extractor.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.HoleAxisExtractor.HoleAxisInfo", "df/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_hole_axis_extractor_1_1_hole_axis_info.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.HoleDetector", "d9/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_hole_detector.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.HoleFeature", "d9/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_hole_feature.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.HoleAxisExtractor.HoleProbeStep", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_hole_axis_extractor_1_1_hole_probe_step.html", null ],
    [ "IEqualityComparer", null, [
      [ "HirEV_SmartFitSystemsApp.Modules.Point3DComparer", "de/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_point3_d_comparer.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.MeshShellGenerator.Point3DComparer", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_mesh_shell_generator_1_1_point3_d_comparer.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.Point3DComparer", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_comparer.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.IgnoredItemManager.IgnoredFaceData", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ignored_item_manager_1_1_ignored_face_data.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.IgnoredItemManager", "dc/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ignored_item_manager.html", null ],
    [ "INotifyPropertyChanged", null, [
      [ "HirEV_SmartFitSystemsApp.ColorToolItem", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_color_tool_item.html", null ],
      [ "HirEV_SmartFitSystemsApp.LogNode", "da/d02/class_hir_e_v___smart_fit_systems_app_1_1_log_node.html", null ],
      [ "HirEV_SmartFitSystemsApp.Measuring_SidePanel", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_measuring___side_panel.html", null ],
      [ "HirEV_SmartFitSystemsApp.Planning_SidePanel", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_planning___side_panel.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomControls.ToleranceSlidersViewModel", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_sliders_view_model.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.EyeshotEntityFilterDialog", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_eyeshot_entity_filter_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.EyeshotEntityFilterDialog.EntityViewModel", "dc/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_eyeshot_entity78997ddff1edc05c62bbbbffe547920d.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.PasswordInputDialog", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_password_input_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.PathEditDialog", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_path_edit_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.ScannerConfigurationDialog", "d9/d01/class_hir_e_v___smart_fit_systems_app_1_1_scanner_configuration_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Settings_SidePanel", "df/d01/class_hir_e_v___smart_fit_systems_app_1_1_settings___side_panel.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.IUndoCommand", "d8/d01/interface_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_i_undo_command.html", [
      [ "HirEV_SmartFitSystemsApp.Utilities.ActionUndoCommand", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_action_undo_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.BroadUndoCommand", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.CompositeCommand", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_composite_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.DeleteWaypointCommand", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_delete_waypoint_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.InsertWaypointCommand", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_insert_waypoint_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.MovePartCommand", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_part_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointBatchCommand", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointCommand", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.TranslatePathsCommand", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_translate_paths_command.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.UpdateColorPathCommand", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_update_color_path_command.html", null ]
    ] ],
    [ "JsonConverter", null, [
      [ "HirEV_SmartFitSystemsApp.Utilities.ColorJsonConverter", "df/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_json_converter.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.EntityJsonConverterFactory.EntityConverterInner< T >", "d8/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_entity_json_converter_factory_1_1_entity_converter_inner-1-g.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.Point3DJsonConverter", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_json_converter.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.Point4DConverter", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point4_d_converter.html", null ],
      [ "HirEV_SmartFitSystemsApp.Utilities.Vector3DJsonConverter", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_vector3_d_json_converter.html", null ]
    ] ],
    [ "JsonConverterFactory", null, [
      [ "HirEV_SmartFitSystemsApp.Utilities.EntityJsonConverterFactory", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_entity_json_converter_factory.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.JsonExportUtils", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_json_export_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.JumpCollisionValidator", "dd/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_jump_collision_validator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.JumpEdge", "d5/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_jump_edge.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.JumpGraph", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_jump_graph.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.JumpGraphBuilder", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_jump_graph_builder.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.JumpNode", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_jump_node.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.JumpPathPlanner", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_jump_path_planner.html", null ],
    [ "HirEV_SmartFitSystemsApp.Windows.MarkerData", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_windows_1_1_marker_data.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.MeasurementPointWithFaceIndex", "d6/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_measurement_point_with_face_index.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MeasuringToolConfigManager", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_measuring_tool_config_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.MeasuringToolTypes", "d9/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_measuring_tool_types.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.MeshShellGenerator", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_mesh_shell_generator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.Configuration.ModelFileInfo", "d9/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_configuration_1_1_model_file_info.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.NearestNeighborTwoOpt", "db/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_nearest_neighbor_two_opt.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.PartBoundingSphere", "d2/d03/struct_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_part_bounding_sphere.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.PartBridgeMoveSnapshot", "df/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_part_bridge_move_snapshot.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.PostProcessors.PartInspectL", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_post_processors_1_1_part_inspect_l.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.PartScanGroup", "dd/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_part_scan_group.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.PathExportDTO", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_path_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager", "d4/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.ViewModel.MainViewModel.PathOwnershipRepairPartBounds", "d7/d00/class_hir_e_v___smart_fit_systems_app_1_1_view_model_1_1_main_view_model_1_1_path_ownership_repair_part_bounds.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Diagnostics.PathPlanningDiagnostics", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics_1_1_path_planning_diagnostics.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathPoint", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_point.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.PathPointExportDTO", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_path_point_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.RRTStarPathfinder.PathResult", "d0/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_r_r_t_star_pathfinder_1_1_path_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.VisibilityGraphPathfinder.PathResult", "dc/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder_1_1_path_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathSegmentData", "df/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_segment_data.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.PathVolumeValidator", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_path_volume_validator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.PathWaypoint", "db/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_path_waypoint.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.PointEditEventDTO", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_point_edit_event_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.PointExportDTO", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_point_export_d_t_o.html", null ],
    [ "ProtectedConfigManager", "dc/d03/class_protected_config_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.ViewModel.RecentPartItem", "d0/d00/class_hir_e_v___smart_fit_systems_app_1_1_view_model_1_1_recent_part_item.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.RecentPartsManager", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_recent_parts_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.RRTStarPathfinder", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_r_r_t_star_pathfinder.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScannerConfig", "d8/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scanner_config.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ScannerConfigurationSaver", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_scanner_configuration_saver.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.ScannerDepthBuffer", "dc/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_scanner_depth_buffer.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.ScannerModel", "d1/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_scanner_model.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.ScannerProperties", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_scanner_properties.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.ScannerPropertiesLoader", "d9/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_scanner_properties_loader.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.ScannerSnapshot", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_scanner_snapshot.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.ScannerTypes", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_scanner_types.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPath", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPathManager", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPathOptions", "d3/d01/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path_options.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPoint", "d7/d00/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_point.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.SdfShellGenerator.SdfContext", "d2/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_sdf_shell_generator_1_1_sdf_context.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.SdfContextCacheDTO", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_sdf_context_cache_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.SdfShellCacheDTO", "d9/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_sdf_shell_cache_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.SdfShellCacheValidationInput", "db/d00/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_sdf_shell_cache_validation_input.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.SdfShellGenerator", "db/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_sdf_shell_generator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.SdfShellModelFingerprintDTO", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_sdf_shell_model_fingerprint_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.SdfShellVisualizer", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_sdf_shell_visualizer.html", null ],
    [ "SecurePasswordManager", "d7/d03/class_secure_password_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.SegmentCollisionValidator", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_segment_collision_validator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.SegmentValidationResult", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_segment_validation_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Diagnostics.PathPlanningDiagnostics.SequenceTestResult", "d0/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics_1_1_path_planning_diagnostics_1_1_sequence_test_result.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.Configuration.SessionConfig", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_configuration_1_1_session_config.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Configuration.SessionConfigurationManager", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_configuration_1_1_session_configuration_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.ShellBasedPathPlanner", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_shell_based_path_planner.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.ShellGeodesicNavigator", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_shell_geodesic_navigator.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.ShellMeshDTO", "db/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_shell_mesh_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.ShellProjectionUtils", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_shell_projection_utils.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.SimulationPathRun", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_simulation_path_run.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.BroadUndoCommand.State", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command_1_1_state.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.SurfaceGridPoint", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_surface_grid_point.html", null ],
    [ "HirEV_SmartFitSystemsApp.Modules.ScanPathManager.SurfaceSample", "d7/d00/struct_hir_e_v___smart_fit_systems_app_1_1_modules_1_1_scan_path_manager_1_1_surface_sample.html", null ],
    [ "ToleranceConfigManager", "d0/d01/class_tolerance_config_manager.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ToolModelLoader", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_tool_model_loader.html", null ],
    [ "HirEV_SmartFitSystemsApp.Models.ToolTransformation", "d5/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_tool_transformation.html", null ],
    [ "TraceListener", null, [
      [ "HirEV_SmartFitSystemsApp.Measuring_SidePanel.TextBoxTraceListener", "dc/d00/class_hir_e_v___smart_fit_systems_app_1_1_measuring___side_panel_1_1_text_box_trace_listener.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.RRTStarPathfinder.TreeNode", "dc/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_r_r_t_star_pathfinder_1_1_tree_node.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.CollisionAvoidanceAlgorithm.Triangle", "dd/d03/struct_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_collision_avoidance_algorithm_1_1_triangle.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.Algorithms.Triangle3D", "d5/d03/struct_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms_1_1_triangle3_d.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UndoHistoryEntryDTO", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_history_entry_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UndoManager", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_manager.html", null ],
    [ "UserControl", null, [
      [ "HirEV_SmartFitSystemsApp.About_SidePanel", "d6/d03/class_hir_e_v___smart_fit_systems_app_1_1_about___side_panel.html", null ],
      [ "HirEV_SmartFitSystemsApp.Measuring_SidePanel", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_measuring___side_panel.html", null ],
      [ "HirEV_SmartFitSystemsApp.Planning_SidePanel", "d6/d01/class_hir_e_v___smart_fit_systems_app_1_1_planning___side_panel.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomControls.ToleranceSliderTemplate", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_slider_template.html", null ],
      [ "HirEV_SmartFitSystemsApp.Settings_SidePanel", "df/d01/class_hir_e_v___smart_fit_systems_app_1_1_settings___side_panel.html", null ]
    ] ],
    [ "ValidationRule", null, [
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.Validation.IPv4ValidationRule", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_validation_1_1_i_pv4_validation_rule.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.Validation.NumericValidationRule", "df/d02/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_validation_1_1_numeric_validation_rule.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Models.DTOs.VectorExportDTO", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_models_1_1_d_t_os_1_1_vector_export_d_t_o.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.VerificationPointData", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_verification_point_data.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.PathManager.VerificationTriangle", "d3/d01/struct_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager_1_1_verification_triangle.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.VisibilityGraphPathfinder", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder.html", null ],
    [ "HirEV_SmartFitSystemsApp.Utilities.WaypointData", "d0/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_waypoint_data.html", null ],
    [ "Window", null, [
      [ "HirEV_SmartFitSystemsApp.MainWindow", "dd/d01/class_hir_e_v___smart_fit_systems_app_1_1_main_window.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.EyeshotEntityFilterDialog", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_eyeshot_entity_filter_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.PasswordInputDialog", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_password_input_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomDialogs.PathEditDialog", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_dialogs_1_1_path_edit_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.ScannerConfigurationDialog", "d9/d01/class_hir_e_v___smart_fit_systems_app_1_1_scanner_configuration_dialog.html", null ],
      [ "HirEV_SmartFitSystemsApp.Windows.SectionViewWindow", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_windows_1_1_section_view_window.html", null ]
    ] ],
    [ "HirEV_SmartFitSystemsApp.Utilities.XmlExportUtils", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_xml_export_utils.html", null ]
];