var namespace_hir_e_v___smart_fit_systems_app_1_1_utilities =
[
    [ "Algorithms", "d6/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms.html", "d6/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_algorithms" ],
    [ "Diagnostics", "df/d00/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics.html", "df/d00/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_diagnostics" ],
    [ "Configuration", "d0/d00/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_configuration.html", "d0/d00/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_configuration" ],
    [ "PathPoint", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_point.html", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_point" ],
    [ "ColorPath", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_path.html", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_path" ],
    [ "ControlPointFilterConfig", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_control_point_filter_config.html", "da/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_control_point_filter_config" ],
    [ "WaypointData", "d0/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_waypoint_data.html", "d0/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_waypoint_data" ],
    [ "PathSegmentData", "df/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_segment_data.html", "df/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_segment_data" ],
    [ "BridgePathConsumer", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path_consumer.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path_consumer" ],
    [ "BridgePath", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path.html", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_bridge_path" ],
    [ "PathManager", "d4/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager.html", "d4/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_manager" ],
    [ "SimulationEventArgs", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_simulation_event_args.html", "d1/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_simulation_event_args" ],
    [ "ColorGroupEventArgs", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group_event_args.html", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group_event_args" ],
    [ "PathGenerationProgressEventArgs", "d9/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_generation_progress_event_args.html", "d9/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_path_generation_progress_event_args" ],
    [ "AntColonyOptimization", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ant_colony_optimization.html", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ant_colony_optimization" ],
    [ "CollisionAvoidanceAlgorithm", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_collision_avoidance_algorithm.html", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_collision_avoidance_algorithm" ],
    [ "RRTStarPathfinder", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_r_r_t_star_pathfinder.html", "d4/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_r_r_t_star_pathfinder" ],
    [ "VisibilityGraphPathfinder", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder.html", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_visibility_graph_pathfinder" ],
    [ "ColorJsonConverter", "df/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_json_converter.html", "df/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_json_converter" ],
    [ "ColorNamer", "d3/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_namer.html", "d3/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_namer" ],
    [ "ColorToolMappingUtils", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_tool_mapping_utils.html", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_tool_mapping_utils" ],
    [ "DynamicToolScanner", "d9/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_dynamic_tool_scanner.html", "d9/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_dynamic_tool_scanner" ],
    [ "EyeshotCameraUtils", "d0/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_camera_utils.html", "d0/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_camera_utils" ],
    [ "EyeshotGeometryUtils", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_geometry_utils.html", "d0/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_geometry_utils" ],
    [ "EyeshotSelectionUtils", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_selection_utils.html", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_selection_utils" ],
    [ "EyeshotTreeViewHelper", "d8/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_tree_view_helper.html", "d8/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_tree_view_helper" ],
    [ "EyeshotVisualsManager", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_visuals_manager.html", "d3/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_eyeshot_visuals_manager" ],
    [ "GridPointGenerator", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_grid_point_generator.html", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_grid_point_generator" ],
    [ "HirEVDesign", "dd/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_hir_e_v_design.html", "dd/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_hir_e_v_design" ],
    [ "IgnoredItemManager", "dc/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ignored_item_manager.html", "dc/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_ignored_item_manager" ],
    [ "JsonExportUtils", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_json_export_utils.html", "d0/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_json_export_utils" ],
    [ "MeasuringToolConfigManager", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_measuring_tool_config_manager.html", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_measuring_tool_config_manager" ],
    [ "Point3DComparer", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_comparer.html", "d7/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_comparer" ],
    [ "Point4DConverter", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point4_d_converter.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point4_d_converter" ],
    [ "Point3DJsonConverter", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_json_converter.html", "d4/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_point3_d_json_converter" ],
    [ "Vector3DJsonConverter", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_vector3_d_json_converter.html", "db/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_vector3_d_json_converter" ],
    [ "EntityJsonConverterFactory", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_entity_json_converter_factory.html", "d1/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_entity_json_converter_factory" ],
    [ "RecentPartsManager", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_recent_parts_manager.html", "d8/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_recent_parts_manager" ],
    [ "ScannerConfigurationSaver", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_scanner_configuration_saver.html", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_scanner_configuration_saver" ],
    [ "ToolModelLoader", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_tool_model_loader.html", "d6/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_tool_model_loader" ],
    [ "IUndoCommand", "d8/d01/interface_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_i_undo_command.html", "d8/d01/interface_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_i_undo_command" ],
    [ "UndoRedoEventArgs", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_redo_event_args.html", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_redo_event_args" ],
    [ "UndoManager", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_manager.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_manager" ],
    [ "UndoHistoryEntryDTO", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_history_entry_d_t_o.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_history_entry_d_t_o" ],
    [ "CompositeCommand", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_composite_command.html", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_composite_command" ],
    [ "UpdateColorPathCommand", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_update_color_path_command.html", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_update_color_path_command" ],
    [ "TranslatePathsCommand", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_translate_paths_command.html", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_translate_paths_command" ],
    [ "BroadUndoCommand", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command.html", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command" ],
    [ "InsertWaypointCommand", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_insert_waypoint_command.html", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_insert_waypoint_command" ],
    [ "MoveWaypointBatchCommand", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command.html", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command" ],
    [ "MoveWaypointCommand", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_command.html", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_command" ],
    [ "DeleteWaypointCommand", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_delete_waypoint_command.html", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_delete_waypoint_command" ],
    [ "MovePartCommand", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_part_command.html", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_part_command" ],
    [ "ActionUndoCommand", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_action_undo_command.html", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_action_undo_command" ],
    [ "ColorGroup", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group.html", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_color_group" ],
    [ "XmlExportUtils", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_xml_export_utils.html", "d5/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_xml_export_utils" ],
    [ "ProbePathPlanningMode", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a7d4e7f10a0c14282ffa90f738a99f3d7", [
      [ "ByColor", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a7d4e7f10a0c14282ffa90f738a99f3d7adf231c8643a1875fd70d9496e3597e4d", null ],
      [ "ByPart", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a7d4e7f10a0c14282ffa90f738a99f3d7a4d180f3539670c678ae3b6e8da2b0b45", null ]
    ] ],
    [ "TrajectoryPlanningMode", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a1ca579b9e54b2e6c2f512efa0ec9cf93", [
      [ "Probe", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a1ca579b9e54b2e6c2f512efa0ec9cf93a76d16796b5fada9968ee2530ea43ddc3", null ],
      [ "Scanner", "d5/d01/namespace_hir_e_v___smart_fit_systems_app_1_1_utilities.html#a1ca579b9e54b2e6c2f512efa0ec9cf93a948505fb20417757f22a4d1143346dd8", null ]
    ] ]
];