var _tolerance_slider_template_8xaml_8cs =
[
    [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomControls.ToleranceSliderTemplate", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_slider_template.html", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_slider_template" ],
    [ "HirEV_SmartFitSystemsApp.Resource_Tools.CustomControls.ToleranceSlidersViewModel", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_sliders_view_model.html", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_resource___tools_1_1_custom_controls_1_1_tolerance_sliders_view_model" ]
];