var _undo_manager_8cs =
[
    [ "HirEV_SmartFitSystemsApp.Utilities.IUndoCommand", "d8/d01/interface_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_i_undo_command.html", "d8/d01/interface_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_i_undo_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UndoRedoEventArgs", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_redo_event_args.html", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_redo_event_args" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UndoManager", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_manager.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_manager" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UndoHistoryEntryDTO", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_history_entry_d_t_o.html", "d2/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_undo_history_entry_d_t_o" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.CompositeCommand", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_composite_command.html", "d5/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_composite_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.UpdateColorPathCommand", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_update_color_path_command.html", "de/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_update_color_path_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.TranslatePathsCommand", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_translate_paths_command.html", "d8/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_translate_paths_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.BroadUndoCommand", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command.html", "da/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.BroadUndoCommand.State", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command_1_1_state.html", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_broad_undo_command_1_1_state" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.InsertWaypointCommand", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_insert_waypoint_command.html", "dd/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_insert_waypoint_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointBatchCommand", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command.html", "d6/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointBatchCommand.ChangeInfo", "da/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command_1_1_change_info.html", "da/d02/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_batch_command_1_1_change_info" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MoveWaypointCommand", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_command.html", "d7/d01/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_waypoint_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.DeleteWaypointCommand", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_delete_waypoint_command.html", "d4/d00/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_delete_waypoint_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.MovePartCommand", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_part_command.html", "d1/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_move_part_command" ],
    [ "HirEV_SmartFitSystemsApp.Utilities.ActionUndoCommand", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_action_undo_command.html", "d2/d03/class_hir_e_v___smart_fit_systems_app_1_1_utilities_1_1_action_undo_command" ]
];